<?php
// dashboard/ai_assistant.php
session_start();
require '../includes/db.php'; // your DB connection ($conn)

if (!isset($_SESSION['user_id'])) {
    header("Location: ../auth/login.php");
    exit();
}

$user_id = intval($_SESSION['user_id']);
$user_name = $_SESSION['name'] ?? 'Student';
$first_name = explode(' ', trim($user_name))[0];
$profile_photo = $_SESSION['profile_photo'] ?? null;

// fetch list of courses for the course selector
$courses = [];
$cr = $conn->query("SELECT DISTINCT course FROM resources WHERE course<>'' ORDER BY course ASC");
if ($cr) {
    while ($r = $cr->fetch_assoc()) $courses[] = $r['course'];
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Assistant | StudyCollabo</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
:root{--primary:#1a73e8;--bg:#f8f9fa;--surface:#fff;--text:#222}
body{background:var(--bg);color:var(--text);font-family:Inter,system-ui,Arial;margin:0;overflow-x:hidden;}
main{margin-left:250px;padding:90px 28px 40px;transition:margin-left .3s}
@media(max-width:768px){ main{margin-left:0!important;padding-top:80px} }

.chat-shell { display:flex; gap:20px; }
.left { flex:1.3; }
.right { width:360px; }

.card-surface { background:var(--surface); border:1px solid #e8e8e8; border-radius:10px; padding:12px; box-shadow:0 2px 8px rgba(0,0,0,0.03); }

.chat-log { height:55vh; overflow:auto; padding:12px; background:#fff; border-radius:8px; border:1px solid #eee; }
.message.user { text-align:right; margin:8px 0; }
.message.user .bubble { display:inline-block; background:#1a73e8; color:#fff; padding:8px 12px; border-radius:12px; max-width:80%; }
.message.ai { text-align:left; margin:8px 0; }
.message.ai .bubble { display:inline-block; background:#f1f3f4; color:#111; padding:8px 12px; border-radius:12px; max-width:80%; position:relative; }
.system-note { font-size:.9rem; color:#666; margin-bottom:8px; }
textarea#userInput { resize:none; height:90px; }
.small-muted{font-size:.85rem;color:#6b7280}
.tips-panel { max-height:40vh; overflow:auto; }
.tips-panel li { margin-bottom:6px; }
.suggest-btn { margin:2px; font-size:.85rem; }
.copy-btn { font-size:.8rem; padding:2px 6px; position:absolute; top:4px; right:4px; cursor:pointer; }
.collapse-content { display:none; margin-top:4px; white-space:pre-wrap; background:#eef1f4; padding:8px; border-radius:6px; border:1px solid #ddd; }
</style>
</head>
<body>
<?php include '../includes/sidebar.php'; ?>
<main>
<?php include '../includes/navbar.php'; ?>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h4 class="m-0">AI Assistant</h4>
    <small class="text-muted">Course-aware coaching, assignment help and study strategies</small>
</div>

<div class="chat-shell">
    <!-- Left: Chat panel -->
    <div class="left">
        <div class="card-surface mb-3">
            <div class="d-flex gap-2 mb-2 align-items-center">
                <select id="courseSelect" class="form-select" style="max-width:320px;">
                    <option value="">General / No course</option>
                    <?php foreach($courses as $c): ?>
                        <option value="<?= htmlspecialchars($c) ?>"><?= htmlspecialchars($c) ?></option>
                    <?php endforeach; ?>
                </select>

                <button class="btn btn-outline-secondary" id="clearChatBtn" title="Clear chat history">Clear</button>
                <button class="btn btn-outline-secondary" id="refreshChatBtn" title="Reload history"><i class="bi bi-arrow-clockwise"></i></button>
            </div>

            <div id="chatLog" class="chat-log" aria-live="polite" aria-atomic="false">
                <div class="system-note">Select a course (optional), ask a question and press Send. Your chat is saved to your history.</div>
            </div>

            <div class="mt-3 d-flex flex-column gap-2">
                <textarea id="userInput" class="form-control" placeholder="Ask the AI — e.g. 'Explain pointers in C with simple examples'"></textarea>
                <div class="d-flex flex-wrap justify-content-start mt-2" id="suggestedQuestions"></div>
                <div class="d-flex justify-content-end gap-2 mt-2">
                    <button id="sendBtn" class="btn btn-primary"><i class="bi bi-robot me-1"></i> Send</button>
                </div>
                <div class="small-muted mt-1">Responses are generated by OpenAI. Do not paste private exam material you aren't allowed to share.</div>
            </div>
        </div>

        <div class="card-surface">
            <h6>Quick tips</h6>
            <ul class="tips-panel mb-0" id="aiTipsList">
                <li>Provide course & topic for more tailored answers.</li>
                <li>Ask for step-by-step solutions, summaries, or practice problems.</li>
                <li>Click suggested questions to ask instantly.</li>
            </ul>
        </div>
    </div>

    <!-- Right: History panel -->
    <div class="right">
        <div class="card-surface mb-3">
            <h6 class="mb-2">Chat History (course)</h6>
            <div id="historyList" style="max-height:60vh; overflow:auto;"></div>
        </div>

        <div class="card-surface">
            <h6 class="mb-2">Session</h6>
            <div class="small-muted">User: <?= htmlspecialchars($first_name) ?></div>
            <div class="small-muted">User ID: <?= $user_id ?></div>
        </div>
    </div>
</div>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
const userId = <?= json_encode($user_id) ?>;
const chatLog = document.getElementById('chatLog');
const courseSelect = document.getElementById('courseSelect');
const sendBtn = document.getElementById('sendBtn');
const userInput = document.getElementById('userInput');
const historyList = document.getElementById('historyList');
const clearChatBtn = document.getElementById('clearChatBtn');
const refreshChatBtn = document.getElementById('refreshChatBtn');
const suggestedQuestions = document.getElementById('suggestedQuestions');
const aiTipsList = document.getElementById('aiTipsList');

function escapeHtml(s){ 
    return String(s||'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); 
}

function scrollChatToBottom() { chatLog.scrollTop = chatLog.scrollHeight; }

async function loadHistory(){
    const course = courseSelect.value || '';
    historyList.innerHTML = 'Loading...';
    chatLog.innerHTML = '<div class="system-note">Loading...</div>';
    try {
        const res = await fetch('ai_assistant_history.php?course=' + encodeURIComponent(course));
        const json = await res.json();
        chatLog.innerHTML = '';
        historyList.innerHTML = '';
        suggestedQuestions.innerHTML = '';
        if(!json.success){
            chatLog.innerHTML = '<div class="system-note text-danger">Failed to load history</div>';
            historyList.innerHTML = '<div class="text-danger">Error</div>';
            return;
        }
        if(json.data.length === 0){
            chatLog.innerHTML = '<div class="system-note">No messages for this course yet.</div>';
            historyList.innerHTML = '<div class="text-muted">No history.</div>';
        }

        // populate chat log and history
        json.data.forEach(m=>{
            if(m.role==='user'){
                const container = document.createElement('div');
                container.className = 'message user';
                const bubble = document.createElement('div');
                bubble.className = 'bubble';
                bubble.innerHTML = '<strong>You:</strong> ' + escapeHtml(m.message);
                container.appendChild(bubble);
                chatLog.appendChild(container);
            } else {
                const container = document.createElement('div');
                container.className = 'message ai';
                const bubble = document.createElement('div');
                bubble.className = 'bubble';
                
                // collapse content
                const toggleBtn = document.createElement('button');
                toggleBtn.className = 'btn btn-sm btn-outline-secondary copy-btn';
                toggleBtn.textContent = 'Copy';
                toggleBtn.onclick = ()=>navigator.clipboard.writeText(m.message);

                const content = document.createElement('div');
                content.className = 'collapse-content';
                content.textContent = m.message;

                const summary = document.createElement('div');
                summary.innerHTML = '<strong>AI Response</strong> <span class="text-muted" style="font-size:.8rem;">('+ new Date(m.created_at).toLocaleString() +')</span>';
                summary.style.cursor='pointer';
                summary.onclick = ()=>content.style.display = content.style.display==='none'?'block':'none';

                bubble.appendChild(toggleBtn);
                bubble.appendChild(summary);
                bubble.appendChild(content);
                container.appendChild(bubble);
                chatLog.appendChild(container);
            }

            // right history item (compact)
            const h = document.createElement('div');
            h.className = 'mb-2';
            h.innerHTML = '<div style="font-weight:600">' + (m.role==='user' ? 'You' : 'AI') + ' • ' + new Date(m.created_at).toLocaleString() + '</div>'
                        + '<div class="small-muted">' + escapeHtml((m.message||'').substring(0,120)) + (m.message.length>120? '...':'') + '</div>';
            historyList.appendChild(h);
        });
        scrollChatToBottom();

        // suggested questions
        const courseName = course || 'General';
        const suggestions = [
            `Explain key concepts in ${courseName}`,
            `Summarize important topics in ${courseName}`,
            `Practice problems for ${courseName}`,
            `Step-by-step explanation for ${courseName} assignment`,
            `Tips for studying ${courseName}`
        ];
        suggestions.forEach(q=>{
            const btn = document.createElement('button');
            btn.className = 'btn btn-outline-primary suggest-btn';
            btn.textContent = q;
            btn.onclick = ()=>{ userInput.value = q; sendMessage(); };
            suggestedQuestions.appendChild(btn);
        });

    } catch (err){
        console.error(err);
        chatLog.innerHTML = '<div class="system-note text-danger">Error loading chat</div>';
        historyList.innerHTML = '<div class="text-danger">Error</div>';
    }
}

async function sendMessage(){
    const text = userInput.value.trim();
    if (!text) return;
    const course = courseSelect.value || '';

    const userDiv = document.createElement('div');
    userDiv.className = 'message user';
    const ub = document.createElement('div'); ub.className='bubble'; ub.innerHTML = '<strong>You:</strong> ' + escapeHtml(text);
    userDiv.appendChild(ub);
    chatLog.appendChild(userDiv);
    scrollChatToBottom();

    userInput.value = '';
    userInput.disabled = true;
    sendBtn.disabled = true;

    const aiDiv = document.createElement('div');
    aiDiv.className = 'message ai';
    const ab = document.createElement('div'); ab.className='bubble'; ab.innerHTML = '<em>Loading...</em>';
    aiDiv.appendChild(ab);
    chatLog.appendChild(aiDiv);
    scrollChatToBottom();

    try {
        const fd = new FormData();
        fd.append('action','send');
        fd.append('message', text);
        fd.append('course', course);
        const res = await fetch('ai_assistant_actions.php', { method:'POST', body:fd });
        const json = await res.json();
        if(!json.success){
            alert(json.message || 'Error from server');
            aiDiv.remove();
            userInput.disabled = false; sendBtn.disabled = false;
            return;
        }

        // replace loading with collapsible AI response
        ab.innerHTML='';
        const toggleBtn = document.createElement('button');
        toggleBtn.className='btn btn-sm btn-outline-secondary copy-btn';
        toggleBtn.textContent='Copy';
        toggleBtn.onclick=()=>navigator.clipboard.writeText(json.ai_response);

        const content = document.createElement('div');
        content.className='collapse-content';
        content.textContent = json.ai_response;

        const summary = document.createElement('div');
        summary.innerHTML='<strong>AI Response</strong>';
        summary.style.cursor='pointer';
        summary.onclick = ()=>content.style.display = content.style.display==='none'?'block':'none';

        ab.appendChild(toggleBtn);
        ab.appendChild(summary);
        ab.appendChild(content);

        scrollChatToBottom();
        loadHistory();
    } catch (err){
        console.error(err);
        alert('Network/server error');
        aiDiv.remove();
    } finally {
        userInput.disabled = false;
        sendBtn.disabled = false;
        userInput.focus();
    }
}

sendBtn.addEventListener('click', sendMessage);
userInput.addEventListener('keydown', e => {
    if(e.key==='Enter' && !e.shiftKey){
        e.preventDefault();
        sendMessage();
    }
});

clearChatBtn.addEventListener('click', async ()=>{
    if(!confirm('Clear chat history for selected course?')) return;
    const course = courseSelect.value || '';
    const fd = new FormData(); fd.append('action','clear'); fd.append('course', course);
    const res = await fetch('ai_assistant_actions.php', { method:'POST', body:fd });
    const json = await res.json();
    if(json.success){
        loadHistory();
        alert('Cleared.');
    } else {
        alert(json.message || 'Clear failed');
    }
});

refreshChatBtn.addEventListener('click', loadHistory);
courseSelect.addEventListener('change', loadHistory);

userInput.focus();
loadHistory();
</script>
</body>
</html>